name: Docker Save
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save
        run: |
          docker pull --platform linux/amd64 browserless/chromium:latest
          docker save browserless/chromium:latest > browser_amd64.tar
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: browser-tar
          path: browser_amd64.tar
